baseURL = "http://example.org/"
languageCode = "en-us"
title = "Accessible Minimalism"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
